"use client";
import {useEffect,useRef,useState} from 'react';
import {Link2,Upload,Sparkles,Box,Loader2,ExternalLink,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {ProductInfo} from '@/lib/editor/product';
type Job={id:string;name:string;width:number;depth:number;height:number;sourceUrl:string};
export type GeneratedProduct=Job&{data:string};
const empty:ProductInfo={name:'',widthCm:null,depthCm:null,heightCm:null,material:'',notes:[],sourceUrl:'',images:[]};
async function photoData(blob:Blob){
 if(blob.size>8_000_000)throw new Error('La photo dépasse 8 Mo.');const bitmap=await createImageBitmap(blob);try{const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.92)}finally{bitmap.close()}
}
export default function ProductDialog({open,onOpenChange,apiKey,meshyKey,model,onSettings,onInsert}:{open:boolean;onOpenChange:(v:boolean)=>void;apiKey:string;meshyKey:string;model:string;onSettings:()=>void;onInsert:(p:GeneratedProduct)=>Promise<void>}){
 const [url,setUrl]=useState(''),[product,setProduct]=useState<ProductInfo>(empty),[photo,setPhoto]=useState(''),[loading,setLoading]=useState(''),[error,setError]=useState(''),[job,setJob]=useState<Job|null>(null),[status,setStatus]=useState(''),[progress,setProgress]=useState(0),[resume,setResume]=useState(0);
 const imageInput=useRef<HTMLInputElement>(null),pending=useRef(false),inFlight=useRef<AbortController|null>(null),imageSequence=useRef(0);
 useEffect(()=>{try{const stored=JSON.parse(sessionStorage.getItem('conceptuo-meshy-job')??'null');if(stored&&typeof stored.id==='string'&&typeof stored.name==='string'&&[stored.width,stored.depth,stored.height].every(n=>typeof n==='number'&&n>0&&n<=20)){setJob(stored);setStatus('PENDING')}}catch{}return()=>{inFlight.current?.abort()}},[]);
 useEffect(()=>{
  if(!job||!meshyKey)return;let stopped=false,timer:ReturnType<typeof setTimeout>|undefined;const controller=new AbortController();
  const poll=async()=>{try{const response=await fetch('/api/generate-product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',key:meshyKey,id:job.id}),signal:controller.signal});const data=await response.json() as {status?:string;progress?:number;error?:string};if(stopped)return;if(!response.ok)throw new Error(data.error??'Suivi indisponible');setStatus(data.status??'PENDING');setProgress(data.progress??0);if(data.status==='FAILED'||data.status==='CANCELED'){setError(data.error??'La génération a été interrompue chez Meshy.');return}if(data.status==='SUCCEEDED'){setError('');return}timer=setTimeout(poll,6000)}catch(e){if(!stopped)setError((e instanceof Error?e.message:'Connexion interrompue')+' Le suivi peut être repris sans relancer la génération.')}};
  void poll();return()=>{stopped=true;controller.abort();if(timer)clearTimeout(timer)};
 },[job,meshyKey,resume]);
 async function chooseImage(image:string){const token=++imageSequence.current;setLoading('Lecture de la photo…');setError('');try{const response=await fetch('/api/product-image?url='+encodeURIComponent(image));if(!response.ok)throw new Error('Photo inaccessible. Importez une photo du produit.');const data=await photoData(await response.blob());if(token===imageSequence.current)setPhoto(data)}catch(e){if(token===imageSequence.current)setError(e instanceof Error?e.message:'Photo inaccessible.')}finally{if(token===imageSequence.current)setLoading('')}}
 async function readProduct(){if(!apiKey){onSettings();return}setLoading('Lecture de la fiche produit…');setError('');setPhoto('');const controller=new AbortController();inFlight.current=controller;try{const response=await fetch('/api/product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,key:apiKey,model}),signal:controller.signal});const data=await response.json() as ProductInfo&{error?:string};if(!response.ok)throw new Error(data.error??'Fiche indisponible');setProduct(data);if(data.images.length)await chooseImage(data.images[0]);else setError('La page ne fournit pas de photo exploitable. Importez une photo du produit.')}catch(e){setProduct({...empty,sourceUrl:url});setError(e instanceof Error?e.message:'Lecture impossible.')}finally{setLoading('');inFlight.current=null}}
 async function start(){if(pending.current||job)return;if(!meshyKey){onSettings();return}pending.current=true;setLoading('Envoi à Meshy…');setError('');try{const response=await fetch('/api/generate-product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start',key:meshyKey,image:photo})});const data=await response.json() as {id?:string;error?:string};if(!response.ok||!data.id)throw new Error(data.error??'Réponse incertaine : vérifiez votre tableau de bord Meshy avant de relancer.');const next={id:data.id,name:product.name,width:product.widthCm!/100,depth:product.depthCm!/100,height:product.heightCm!/100,sourceUrl:product.sourceUrl||url};setJob(next);setStatus('PENDING');setProgress(0);try{sessionStorage.setItem('conceptuo-meshy-job',JSON.stringify(next))}catch{}}catch(e){setError((e instanceof Error?e.message:'Envoi interrompu')+' En cas de doute, vérifiez Meshy avant de créer une nouvelle génération.')}finally{setLoading('');pending.current=false}}
 async function insert(){if(!job)return;setLoading('Téléchargement du modèle et des textures…');setError('');try{const response=await fetch('/api/generate-product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'download',key:meshyKey,id:job.id})});if(!response.ok){const d=await response.json() as {error?:string};throw new Error(d.error??'Téléchargement impossible')}const blob=await response.blob();const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve((r.result as string).replace(/^data:[^;]*;/,'data:model/gltf-binary;'));r.onerror=reject;r.readAsDataURL(blob)});await onInsert({...job,data});try{sessionStorage.removeItem('conceptuo-meshy-job')}catch{}setJob(null);setStatus('');setPhoto('');setProduct(empty);onOpenChange(false)}catch(e){setError(e instanceof Error?e.message:'Import impossible.')}finally{setLoading('')}}
 const dimensions=[product.widthCm,product.depthCm,product.heightCm];const valid=product.name.trim()&&photo&&dimensions.every(n=>n!==null&&n>=5&&n<=2000)&&product.heightCm!<=1000;
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="product-dialog"><DialogTitle>Un produit du commerce, dans votre projet</DialogTitle><DialogDescription>Photo du produit → modèle 3D texturé → mise aux dimensions réelles. La reconstruction est générée par Meshy.</DialogDescription>
 {job?<div className="generation-job"><Box/><h3>{job.name}</h3><p>{status==='SUCCEEDED'?'Modèle texturé prêt à intégrer':status==='FAILED'?'La génération n’a pas abouti':'Génération en cours chez Meshy'}</p><progress value={progress} max={100}/><span>{Math.round(progress)} % · {job.width.toFixed(2)} × {job.depth.toFixed(2)} × {job.height.toFixed(2)} m</span><p className="small-text">Vous pouvez fermer cette fenêtre et continuer à aménager. Fermer la fenêtre n’annule pas la génération chez Meshy.</p>{!meshyKey&&<button className="outline-button" onClick={onSettings}>Reconnecter Meshy pour reprendre le suivi</button>}{error&&<div className="inline-error" role="alert">{error}<button className="outline-button" onClick={()=>{setError('');setResume(v=>v+1)}}>Reprendre le suivi</button></div>}<div className="dialog-actions"><a className="plain-button" href="https://www.meshy.ai/workspace" target="_blank" rel="noreferrer"><ExternalLink/> Ouvrir Meshy</a>{status==='FAILED'||status==='CANCELED'?<button className="outline-button" onClick={()=>{setJob(null);setError('');sessionStorage.removeItem('conceptuo-meshy-job')}}>Préparer un autre essai</button>:<button className="primary-button" disabled={status!=='SUCCEEDED'||!!loading||!meshyKey} onClick={()=>void insert()}>{loading?<Loader2 className="animate-spin"/>:<PlusIcon/>}Ajouter au projet</button>}</div>{loading&&<p className="small-text">{loading}</p>}<details className="small-text"><summary>Identifiant de génération</summary>{job.id}</details></div>:<>
 <div className="url-row"><label className="form-label">Lien de la fiche produit<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.ikea.com/fr/fr/p/…"/></label><button className="outline-button" disabled={!url||!!loading} onClick={()=>void readProduct()}><Link2/> Lire la fiche</button></div><p className="small-text">IKEA, Leroy Merlin, Castorama, Maisons du Monde, La Redoute, Alinéa, Conforama, BUT et Tikamoon. Si une page bloque la lecture, ajoutez la photo et les dimensions ci-dessous.</p>
 <div className="product-form-grid"><div><div className="product-photo">{photo?<img src={photo} alt="Photo de référence du produit"/>:<Box/>}<span>Photo de référence</span></div>{product.images.length>1&&<div className="photo-choices">{product.images.map((image,i)=><button key={image} className="outline-button" disabled={!!loading} onClick={()=>void chooseImage(image)}>Photo {i+1}</button>)}</div>}<input ref={imageInput} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;++imageSequence.current;setError('');try{setPhoto(await photoData(f))}catch(err){setError(err instanceof Error?err.message:'Photo invalide')}}}/><button className="outline-button full" disabled={!!loading} onClick={()=>imageInput.current?.click()}><Upload/> Choisir une photo</button></div><div className="product-fields"><label className="form-label">Nom du produit<input value={product.name} maxLength={120} onChange={e=>setProduct(p=>({...p,name:e.target.value}))}/></label><div className="product-dimensions">{(['widthCm','depthCm','heightCm']as const).map((key,i)=><label className="form-label" key={key}>{['Largeur','Profondeur','Hauteur'][i]} (cm)<input type="number" min={5} max={i===2?1000:2000} value={product[key]??''} placeholder="À vérifier" onChange={e=>setProduct(p=>({...p,[key]:e.target.value===''?null:Number(e.target.value)}))}/></label>)}</div><p className="small-text">Vérifiez les dimensions du produit, et non celles de son emballage. Une photo isolée de trois quarts donne généralement une référence plus exploitable.</p>{product.material&&<p className="material-note">{product.material}</p>}{product.notes.map((n,i)=><p className="small-text" key={i}>{n}</p>)}</div></div>
 {error&&<p className="inline-error" role="alert">{error}</p>}{loading&&<p className="loading-line"><Loader2 className="animate-spin"/>{loading}</p>}<div className="generation-notice"><Sparkles/><p>La génération utilise les crédits de votre compte Meshy. Le modèle reproduit l’apparence de la photo ; les parties cachées sont reconstruites par l’IA. Les dimensions ci-dessus seront appliquées lors de l’import.</p></div><div className="dialog-actions"><button className="outline-button" onClick={onSettings}>Connexions IA</button><button className="primary-button" disabled={!valid||!!loading} onClick={()=>void start()}><Sparkles/> Générer le modèle 3D</button></div></>}
 </DialogContent></Dialog>
}
function PlusIcon(){return <Check/>}
